(in-package #:mud)

(defvar *registered-players* (make-hash-table :test #'equal))
(defvar *players-by-username* (make-hash-table :test #'equal))
(defvar *password-salt* "mud-server-salt-2024")

(defun hash-password (password)
  (format nil "~X" (abs (sxhash (concatenate 'string password *password-salt*)))))

(defun player-exists-p (username) (gethash username *registered-players*))

(defun register-new-account (session stream)
  (player-send-message session "Choose a username:")
  (player-send-prompt session)
  (let ((username (string-downcase (string-trim '(#\Return #\Newline) (read-line stream)))))
    (if (player-exists-p username)
        (player-send-message session "Taken.")
        (progn
          (player-send-message session "Choose a password:")
          (player-send-prompt session)
          (let ((password (string-trim '(#\Return #\Newline) (read-line stream))))
            (player-send-message session "Display name:")
            (player-send-prompt session)
            (let ((display (string-trim '(#\Return #\Newline) (read-line stream))))
              (let ((character (make-instance 'mud-character :id (mud.utils:make-id) :name display)))
                (setf (gethash username *registered-players*) (list :password-hash (hash-password password)))
                (setf (gethash username *players-by-username*) character)
                (setf (session-character session) character)
                (setf (session-username session) username)
                (player-send-message session "Registered!")
                character)))))))

(defun login-returning-player (session stream)
  (player-send-message session "Username:")
  (player-send-prompt session)
  (let ((username (string-downcase (string-trim '(#\Return #\Newline) (read-line stream)))))
    (let ((info (player-exists-p username)))
      (if (not info) (player-send-message session "No such user.")
          (progn
            (player-send-message session "Password:")
            (player-send-prompt session)
            (let ((password (string-trim '(#\Return #\Newline) (read-line stream))))
              (if (string= (hash-password password) (getf info :password-hash))
                  (let ((character (gethash username *players-by-username*)))
                    (setf (session-character session) character)
                    (setf (session-username session) username)
                    (player-send-message session "Logged in!")
                    character)
                  (player-send-message session "Wrong password."))))))))
